# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd121a2b644ec21eaca33d6231e1390a4e6ed1a93cb52db789097ddcb320db2f9798e81d868c9f30c416cc28beb8aadb04796b786e9d77e850ee3b9fdb44c7be

test:
  secret_key_base: 00fd3f4620a0339a5f77071982680fed30bbad9403a81a1a492894a8b6b3bdc08a01cabc491a413f729c74fbbda2af8548a94254040927d18a008278e98a2b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
